AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) of the form x.x.x.x/x for this VPC
    Type: String
    MinLength: 9
    MaxLength: 18
    #AllowedPattern: (\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})
    Default: 10.192.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    MinLength: 9
    MaxLength: 18
    #AllowedPattern: (\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})
    Default: 10.192.10.0/24

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) of the form x.x.x.x/x for the public subnet in the second Availability Zone
    Type: String
    MinLength: 9
    MaxLength: 18
    #AllowedPattern: (\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})
    Default: 10.192.11.0/24

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) of the form x.x.x.x/x  for the private subnet in the first Availability Zone
    Type: String
    Default: 10.192.20.0/24

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) of the form x.x.x.x/x for the private subnet in the second Availability Zone
    Type: String
    MinLength: 9
    MaxLength: 18
    #AllowedPattern: (\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})
    Default: 10.192.21.0/24
    
Resources:
  NestedStack:
    Type: 'AWS::CloudFormation::Stack'
    #DeletionPolicy: Retain
    Properties:
      TemplateURL: >-
        https://s3.amazonaws.com/playground-configuration/vpc.yaml
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        EnvironmentName: !Ref EnvironmentName
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
